# Site settings
name: Victoria Tran
title: Victoria Tran | PhD candidate in Sociology | UCLA
description: Victoria Tran is a PhD candidate in the Sociology department at UCLA.
url: "https://tranvictoria.com"
baseurl: ""
email: vlt6cp@ucla.edu

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
